import os
Import ('env')

prog_objects = env.Object (Split ("""
	     main.c
	     """))
prog = env.Program (target='syx', source=prog_objects, LIBS=['syx'])
Default (prog)

inst = env.Install (env['bindir'], prog)
env.Alias ('install', env['bindir'])

# Create the image once installed

image = env.Command (env['imagepath'], inst, '$SOURCE -S')
env.AlwaysBuild (image)
env.Depends (image, os.path.join(env['datadir'], 'st'))
env.Alias ('install', image)
env.Clean ('install', image)