Import ('env')

penv = env.Clone ()
    
if penv['PLATFORM'] == 'win32':
    penv.MergeFlags ('-DBUILD_DLL')
     
dirs = []

if penv['GTK']:
    dirs.append ('gtk')
if penv['READLINE']:
    dirs.append ('readline')

SConscript (dirs=dirs, exports=['penv'])
