@c -*-texinfo-*-
@c This is part of the Smalltalk YX Manual.
@c Copyright (C) 2008
@c   Luca Bruno <lethalman88@gmail.com>
@c See the file syx.texi for copying conditions.

@menu
* Objects::
* Variables::
* Methods::
* Messages::
* Inheritance::
* Syntax::
* Class definition::
* Life of objects: Garbage collector.
@end menu

@node Objects
@section Objects

@include objects.texi

@node Variables
@section Variables

@include variables.texi

@node Methods
@section Methods

@include methods.texi

@node Messages
@section Messages

@include messages.texi

@node Inheritance
@section Inheritance

@node Syntax
@section Syntax

@node Class definition
@section Class definition

@node Garbage collector
@section Life of objects: Garbage collector
