Syx: syx/syx-memory.h File Reference
syx-memory.h File Reference
#include "syx-config.h"
#include "syx-platform.h"
#include "syx-object.h"
#include "syx-init.h"
Functions
EXPORT void syx_memory_init (syx_int32 size)
EXPORT void syx_memory_clear (void)
EXPORT SyxOop syx_memory_alloc (void)
EXPORT void syx_memory_gc (void)
EXPORT syx_bool syx_memory_save_image (syx_symbol path)
EXPORT syx_bool syx_memory_load_image (syx_symbol path)
INLINE void syx_memory_free (SyxOop oop)
INLINE syx_int32 syx_memory_get_size (void)
INLINE void syx_memory_gc_begin (void)
EXPORT void syx_memory_gc_end (void)
Function Documentation
EXPORT SyxOop syx_memory_alloc (void)
Returns a new SyxOop
Definition at line 183 of file syx-memory.c.
Referenced by syx_build_basic(), syx_object_copy(), and syx_object_new_vars().
EXPORT void syx_memory_clear (void)
Clears all the allocated memory
Definition at line 142 of file syx-memory.c.
Referenced by syx_build_basic(), and syx_quit().
INLINE void syx_memory_free (SyxOop oop)
Frees the memory of a SyxOop and saves it to be reused for the next syx_memory_alloc
Definition at line 53 of file syx-memory.h.
Referenced by syx_dictionary_rehash(), and syx_object_free().
EXPORT void syx_memory_gc (void)
Calls the Syx garbage collector
Definition at line 295 of file syx-memory.c.
Referenced by syx_memory_alloc(), and syx_memory_save_image().
INLINE void syx_memory_gc_begin (void)
Begins a garbage collection transaction.
In this transaction, all objects being allocated must not be freed because marked. The transaction can hold up to 256 objects.
Definition at line 74 of file syx-memory.h.
Referenced by syx_interp_frame_to_context(), and syx_method_context_new().
EXPORT void syx_memory_gc_end (void)
Release a transaction started with syx_memory_gc_begin and unmark all objects in the transaction
Definition at line 954 of file syx-memory.c.
Referenced by syx_interp_frame_to_context(), and syx_method_context_new().
INLINE syx_int32 syx_memory_get_size (void)
Returns the size of the memory
Definition at line 62 of file syx-memory.h.
EXPORT void syx_memory_init (syx_int32 mem_size)
Initialize or realloc the memory according to the given size
Definition at line 109 of file syx-memory.c.
Referenced by syx_build_basic(), and syx_memory_load_image().
EXPORT syx_bool syx_memory_load_image (syx_symbol path)
Loads the memory.
Parameters:
path the file containing the data dumped by syx_memory_save_image
Returns:
FALSE if an error occurred
Definition at line 840 of file syx-memory.c.
EXPORT syx_bool syx_memory_save_image (syx_symbol path)
Dumps all the memory.
Parameters:
path the file path to put all inside
Returns:
FALSE if an error occurred
Definition at line 594 of file syx-memory.c.
Documented by Luca Bruno and ScaccoMatto