Syx: syx/syx-error.h File Reference
syx-error.h File Reference
#include <stdio.h>
#include "syx-types.h"
#include "syx-config.h"
#include "syx-utils.h"
#include <stdarg.h>
Data Structures
struct SyxErrorEntry
Defines
#define syx_debug printf
Typedefs
typedef struct SyxErrorEntry SyxErrorEntry
Functions
EXPORT void syx_error_init (void)
EXPORT void syx_error_clear (void)
EXPORT SyxErrorType syx_error_register (syx_symbol name, SyxOop klass)
EXPORT SyxErrorEntry * syx_error_lookup (SyxErrorType type)
EXPORT syx_bool syx_signal (SyxErrorType type, SyxOop message)
EXPORT SyxOop syx_signal_create_context (SyxErrorType type, SyxOop message)
EXPORT void syx_warning (syx_symbol fmt,...)
EXPORT void syx_error (syx_symbol fmt,...)
EXPORT void syx_perror (syx_symbol message)
EXPORT syx_bool syx_signal_does_not_understand (SyxOop receiver, SyxOop selector)
Variables
SYX_BEGIN_DECLS typedef syx_uint32 SyxErrorType
Define Documentation
#define syx_debug printf
Display debugging messages
Definition at line 66 of file syx-error.h.
Referenced by syx_interp_call_primitive(), syx_interp_leave_and_answer(), syx_memory_gc(), syx_plugin_load(), syx_plugin_unload(), and syx_scheduler_run().
Typedef Documentation
typedef struct SyxErrorEntry SyxErrorEntry
Definition at line 43 of file syx-error.h.
Function Documentation
EXPORT void syx_error (syx_symbol fmt, ...)
Display an error then exits.
This function will show an error MessageBox on Windows CE
Definition at line 206 of file syx-error.c.
Referenced by syx_cold_file_in(), syx_dictionary_at_symbol_put(), syx_memory_alloc(), syx_object_get_class(), syx_send_binary_message(), syx_send_unary_message(), syx_signal(), syx_symbol_new(), and syx_vsend_message().
EXPORT void syx_error_clear (void)
Clear all memory allocated to by the error reporting system.
This function must be called after all other memory has been released and we're really ready to quit, so that any other call won't report errors. Usually, user programs don't need to call this directly.
Definition at line 74 of file syx-error.c.
Referenced by syx_quit().
EXPORT void syx_error_init (void)
Initialize the error reporting system.
This function must be called after the image has been loaded or a new image is built. Usually, user programs don't need to call this directly.
Definition at line 52 of file syx-error.c.
Referenced by syx_fetch_basic().
EXPORT SyxErrorEntry* syx_error_lookup (SyxErrorType type)
Lookup for an error.
Parameters:
type the type return from syx_error_register
Returns:
the entry of the error
Definition at line 110 of file syx-error.c.
Referenced by syx_signal(), and syx_signal_create_context().
EXPORT SyxErrorType syx_error_register (syx_symbol name, SyxOop klass)
Register a kind of error.
Create a new hook for reporting errors from C to the Smalltalk environment.
Returns:
a number identifying the king of error for future lookups
Definition at line 87 of file syx-error.c.
EXPORT void syx_perror (syx_symbol message)
Display perror message and exit
Definition at line 238 of file syx-error.c.
EXPORT syx_bool syx_signal (SyxErrorType type, SyxOop message)
Signal an error in the Smalltalk environment, sending signal to he requested class.
Parameters:
type the type returned by syx_error_register
Returns:
TRUE if signal succeeded, otherwise FALSE
Definition at line 125 of file syx-error.c.
Referenced by syx_dictionary_at_symbol(), syx_dictionary_bind(), syx_dictionary_bind_set_value(), and syx_dictionary_binding_at_symbol().
EXPORT SyxOop syx_signal_create_context (SyxErrorType type, SyxOop message)
Create an error Context in the Smalltalk environment ready to enter a Process.
Parameters:
type the type returned by syx_error_register
Definition at line 167 of file syx-error.c.
EXPORT syx_bool syx_signal_does_not_understand (SyxOop receiver, SyxOop selector)
Useful stuff
Send receiver>>doesNotUnderstand: with selector.
Parameters:
receiver
selector
Definition at line 191 of file syx-error.c.
EXPORT void syx_warning (syx_symbol fmt, ...)
Display a warning message
Definition at line 227 of file syx-error.c.
Variable Documentation
SYX_BEGIN_DECLS typedef syx_uint32 SyxErrorType
Definition at line 41 of file syx-error.h.
Documented by Luca Bruno and ScaccoMatto