Syx: syx/syx-init.c File Reference
syx-init.c File Reference
#include "syx-memory.h"
#include "syx-types.h"
#include "syx-error.h"
#include "syx-plugins.h"
#include "syx-init.h"
#include "syx-signal.h"
#include "syx-utils.h"
#include "syx-scheduler.h"
#include "syx-object.h"
#include "syx-interp.h"
#include "syx-profile.h"
#include <unistd.h>
#include <assert.h>
#include <stdio.h>
Functions
syx_string syx_find_file (syx_symbol domain, syx_symbol package, syx_symbol filename)
void syx_build_basic (void)
void syx_fetch_basic (void)
void syx_initialize_system (void)
syx_bool syx_init (syx_varsize argc, syx_string *argv, syx_symbol root_path)
void syx_quit (void)
syx_symbol syx_get_root_path (void)
syx_bool syx_set_root_path (syx_symbol root_path)
syx_bool syx_set_image_path (syx_symbol image_path)
syx_symbol syx_get_image_path (void)
Variables
syx_bool syx_system_initialized = FALSE
Function Documentation
void syx_build_basic (void)
Builds a basic running image from scratch.
This functions first reinitialize the memory with the size defined in SYX_INIT_MEMORY_SIZE. After, creates the 3 common constants syx_nil, syx_true and syx_false. Then creates all the classes needed by the VM, the Smalltalk dictionary and a dictionary containing all the symbols. Sets up the basic object hierarchy and insert each class into Smalltalk. Ends up this process by fileing in the basic declarations from initialDecl.st and the other *.st files, and calls syx_fetch_basic to fetch all classes in the VM. Finally, prepares the environment by running a blocking Process that calls Smalltalk>>initializeFirstSystem and initialize everything else from within Smalltalk itself.
Definition at line 183 of file syx-init.c.
void syx_fetch_basic (void)
Definition at line 278 of file syx-init.c.
Referenced by syx_build_basic(), and syx_memory_load_image().
syx_string syx_find_file (syx_symbol domain, syx_symbol package, syx_symbol filename)
Creates a file path inside the Syx environment
For example if you want a Smalltalk file of a package, specify the domain "st", the package name and the file name.
Definition at line 77 of file syx-init.c.
syx_symbol syx_get_image_path (void)
Returns the initial image path.
This path won't be used once Syx is initialized. The image path will be obtained from the ImageFileName global
Definition at line 481 of file syx-init.c.
Referenced by syx_memory_load_image().
syx_symbol syx_get_root_path (void)
Returns the root directory of Syx.
Returns:
a constant string containing the path of the root directory
Definition at line 424 of file syx-init.c.
syx_bool syx_init (syx_varsize argc, syx_string * argv, syx_symbol root_path)
Setup the basic external environment of Syx, such as the root and the image path.
Parameters:
root_path an arbitrary root directory for Syx or NULL
Definition at line 347 of file syx-init.c.
void syx_initialize_system (void)
Remove Smalltalk startupProcess from being scheduled and send startupSystem: to Smalltalk in a scheduled process
Definition at line 318 of file syx-init.c.
Referenced by syx_memory_load_image().
void syx_quit (void)
Finalize Syx.
Run special tasks to finalize the Syx process, such as clearing all the allocated memory
Definition at line 404 of file syx-init.c.
syx_bool syx_set_image_path (syx_symbol image_path)
Sets the initial image path
Definition at line 463 of file syx-init.c.
syx_bool syx_set_root_path (syx_symbol root_path)
Sets the root directory of Syx.
Parameters:
root_path the new path
Returns:
TRUE if the path exists and is readable
Definition at line 436 of file syx-init.c.
Referenced by syx_init().
Variable Documentation
syx_bool syx_system_initialized = FALSE
Definition at line 59 of file syx-init.c.
Referenced by syx_initialize_system(), syx_object_initialize(), and syx_signal().
Documented by Luca Bruno and ScaccoMatto