Syx: syx/syx-memory.c File Reference
syx-memory.c File Reference
#include "syx-config.h"
#include "syx-memory.h"
#include "syx-object.h"
#include "syx-error.h"
#include "syx-scheduler.h"
#include "syx-utils.h"
#include "syx-interp.h"
#include "syx-profile.h"
#include <assert.h>
#include <unistd.h>
#include <stdio.h>
#include <string.h>
#include <gmp.h>
Data Structures
struct SyxMemoryLazyPointer
Defines
#define SYX_MEMORY_TOP (&syx_memory[_syx_memory_size - 1])
Typedefs
typedef struct SyxMemoryLazyPointer SyxMemoryLazyPointer
Enumerations
enum SyxMemoryType {
SYX_MEMORY_TYPE_IMMEDIATE, SYX_MEMORY_TYPE_OBJECT, SYX_MEMORY_TYPE_FRAME_POINTER, SYX_MEMORY_TYPE_NORMAL,
SYX_MEMORY_TYPE_LARGE_INTEGER, SYX_MEMORY_TYPE_BOF, SYX_MEMORY_TYPE_EOS
}
Functions
void syx_memory_init (syx_int32 mem_size)
void syx_memory_clear (void)
SyxOop syx_memory_alloc (void)
void syx_memory_gc (void)
syx_bool syx_memory_save_image (syx_symbol path)
syx_bool syx_memory_load_image (syx_symbol path)
void syx_memory_gc_end (void)
Variables
SyxObject * syx_memory
Define Documentation
#define SYX_MEMORY_TOP (&syx_memory[_syx_memory_size - 1])
Definition at line 56 of file syx-memory.c.
Referenced by syx_memory_clear(), syx_memory_init(), and syx_memory_save_image().
Typedef Documentation
typedef struct SyxMemoryLazyPointer SyxMemoryLazyPointer
Definition at line 71 of file syx-memory.c.
Enumeration Type Documentation
enum SyxMemoryType
Enumerator:
SYX_MEMORY_TYPE_IMMEDIATE
SYX_MEMORY_TYPE_OBJECT
SYX_MEMORY_TYPE_FRAME_POINTER
SYX_MEMORY_TYPE_NORMAL
SYX_MEMORY_TYPE_LARGE_INTEGER
SYX_MEMORY_TYPE_BOF
SYX_MEMORY_TYPE_EOS
Definition at line 58 of file syx-memory.c.
Function Documentation
SyxOop syx_memory_alloc (void)
Returns a new SyxOop
Definition at line 183 of file syx-memory.c.
Referenced by syx_build_basic(), syx_object_copy(), and syx_object_new_vars().
void syx_memory_clear (void)
Clears all the allocated memory
Definition at line 142 of file syx-memory.c.
Referenced by syx_build_basic(), and syx_quit().
void syx_memory_gc (void)
Calls the Syx garbage collector
Definition at line 295 of file syx-memory.c.
Referenced by syx_memory_alloc(), and syx_memory_save_image().
void syx_memory_gc_end (void)
Release a transaction started with syx_memory_gc_begin and unmark all objects in the transaction
Definition at line 954 of file syx-memory.c.
Referenced by syx_interp_frame_to_context(), and syx_method_context_new().
void syx_memory_init (syx_int32 mem_size)
Initialize or realloc the memory according to the given size
Definition at line 109 of file syx-memory.c.
Referenced by syx_build_basic(), and syx_memory_load_image().
syx_bool syx_memory_load_image (syx_symbol path)
Loads the memory.
Parameters:
path the file containing the data dumped by syx_memory_save_image
Returns:
FALSE if an error occurred
Definition at line 840 of file syx-memory.c.
syx_bool syx_memory_save_image (syx_symbol path)
Dumps all the memory.
Parameters:
path the file path to put all inside
Returns:
FALSE if an error occurred
Definition at line 594 of file syx-memory.c.
Variable Documentation
SyxObject* syx_memory
Definition at line 50 of file syx-memory.c.
Referenced by syx_fetch_basic(), and syx_show_traceback().
Documented by Luca Bruno and ScaccoMatto