Syx: syx/syx-plugins.h File Reference
syx-plugins.h File Reference
#include "syx-platform.h"
#include "syx-interp.h"
Data Structures
struct SyxPluginEntry
Typedefs
typedef typedefSYX_BEGIN_DECLS
struct SyxPluginEntry SyxPluginEntry
typedef syx_bool(* SyxPluginInitializeFunc)(void)
typedef void(* SyxPluginFinalizeFunc)(void)
Functions
EXPORT syx_pointer syx_library_open (syx_symbol location)
EXPORT syx_pointer syx_library_symbol (syx_pointer handle, syx_symbol name)
EXPORT syx_bool syx_library_close (syx_pointer handle)
EXPORT void syx_plugins_init (void)
EXPORT void syx_plugins_quit (void)
EXPORT void syx_plugin_finalize_all (void)
EXPORT syx_pointer syx_plugin_load (syx_symbol name)
EXPORT syx_bool syx_plugin_unload (syx_symbol name)
EXPORT syx_pointer syx_plugin_symbol (syx_symbol plugin_name, syx_symbol func_name)
EXPORT syx_bool syx_plugin_call_interp (SyxInterpState *es, SyxOop method)
EXPORT syx_bool syx_plugin_call (SyxInterpState *es, syx_symbol plugin_name, syx_symbol func_name, SyxOop method)
Typedef Documentation
typedef typedefSYX_BEGIN_DECLS struct SyxPluginEntry SyxPluginEntry
Definition at line 33 of file syx-plugins.h.
typedef void(* SyxPluginFinalizeFunc)(void)
Definition at line 53 of file syx-plugins.h.
typedef syx_bool(* SyxPluginInitializeFunc)(void)
Definition at line 52 of file syx-plugins.h.
Function Documentation
EXPORT syx_bool syx_library_close (syx_pointer handle)
Close a library handle.
Parameters:
handle the handle retruedn by syx_library_open
Returns:
FALSE if the handle exists but can't be closed
Definition at line 204 of file syx-plugins.c.
Referenced by syx_plugin_finalize_all(), and syx_plugin_unload().
EXPORT syx_pointer syx_library_open (syx_symbol location)
Load a dynamic library and return its handle.
Parameters:
location the location of the library
Returns:
A pointer to the handle or NULL
Definition at line 141 of file syx-plugins.c.
Referenced by syx_plugin_load().
EXPORT syx_pointer syx_library_symbol (syx_pointer handle, syx_symbol name)
Resolve a symbol in a library.
Parameters:
handle the handle returned by syx_library_open
name the symbol name
Returns:
A pointer to the symbol or NULL
Definition at line 171 of file syx-plugins.c.
Referenced by syx_plugin_finalize_all(), syx_plugin_load(), syx_plugin_symbol(), and syx_plugin_unload().
EXPORT syx_bool syx_plugin_call (SyxInterpState * es, syx_symbol plugin_name, syx_symbol func_name, SyxOop method)
Calls a function of a plugin from within the interpreter.
If the plugin is not loaded yet, then load the plugin and call the requested primitive.
Parameters:
es the execution state
plugin_name the name of the plugin
func_name the name of the function to be called
method method to execute if the primitive fails or syx_nil
Returns:
FALSE to yield the process
Definition at line 474 of file syx-plugins.c.
Referenced by syx_plugin_call_interp().
EXPORT syx_bool syx_plugin_call_interp (SyxInterpState * es, SyxOop method)
Calls a function of a plugin from within the interpreter.
If the plugin is not loaded yet, then load the plugin and call the requested primitive.
Parameters:
es the execution state
method method in which the primitive call has been requested
Returns:
FALSE to yield the process
Definition at line 440 of file syx-plugins.c.
EXPORT void syx_plugin_finalize_all (void)
Finalize all plugins.
This function is usually called internally and user programs don't need to call this manually.
Definition at line 363 of file syx-plugins.c.
Referenced by syx_plugins_quit().
EXPORT syx_pointer syx_plugin_load (syx_symbol name)
Open a dynamic library and initialize the plugin.
Parameters:
name the name of the plugin
Returns:
A pointer to the plugin handle or NULL
Definition at line 233 of file syx-plugins.c.
Referenced by syx_plugin_symbol().
EXPORT syx_pointer syx_plugin_symbol (syx_symbol plugin_name, syx_symbol symbol_name)
Lookup a symbol of the given plugin.
If the plugin is not loaded yet, then load the plugin.
Returns:
the pointer to the looked up symbol or NULL
Definition at line 399 of file syx-plugins.c.
Referenced by syx_plugin_call().
EXPORT syx_bool syx_plugin_unload (syx_symbol plugin)
Close the library handle and finalize the plugin.
This function finalize the plugin but it's not sure it closes the library handler.
Parameters:
handler the plugin handler
Returns:
FALSE if the handler exists but can't be closed
Definition at line 320 of file syx-plugins.c.
EXPORT void syx_plugins_init (void)
Initialize the plugin system.
This function is called internally, usually applications don't need to use this function directly.
Definition at line 58 of file syx-plugins.c.
Referenced by syx_fetch_basic().
EXPORT void syx_plugins_quit (void)
Finalize the plugin system and all loaded plugins.
This function is called internally, usually applications don't need to use this function directly.
Definition at line 99 of file syx-plugins.c.
Referenced by syx_quit().
Documented by Luca Bruno and ScaccoMatto