Syx: syx/syx-scheduler.c File Reference
syx-scheduler.c File Reference
#include "syx-object.h"
#include "syx-types.h"
#include "syx-enums.h"
#include "syx-scheduler.h"
#include "syx-utils.h"
#include "syx-error.h"
#include "syx-interp.h"
#include "syx-memory.h"
#include "syx-init.h"
#include "syx-profile.h"
Functions
void syx_scheduler_init (void)
syx_bool syx_scheduler_iterate (void)
void syx_scheduler_run (void)
void syx_scheduler_poll_register_source (SyxSchedulerSourceFunc callback, SyxOop semaphore)
void syx_scheduler_poll_unregister_source (SyxSchedulerSourceFunc callback, SyxOop semaphore)
void syx_scheduler_quit (void)
syx_bool syx_scheduler_add_process (SyxOop process)
syx_bool syx_scheduler_remove_process (SyxOop process)
Variables
SyxOop syx_processor
Function Documentation
syx_bool syx_scheduler_add_process (SyxOop process)
Add a Process to be scheduled.
Parameters:
process a valid Process
Returns:
TRUE if the given Process has been scheduled successfully, FALSE otherwise
Definition at line 209 of file syx-scheduler.c.
Referenced by syx_process_new().
void syx_scheduler_init (void)
Initialize the scheduler.
If absent, create a ProcessorScheduler instance named Processor and insert it into the Smalltalk dictionary.
Definition at line 97 of file syx-scheduler.c.
Referenced by syx_fetch_basic().
syx_bool syx_scheduler_iterate (void)
Do a single iteration of the scheduler. Returns FALSE when no pending processes are left.
Definition at line 118 of file syx-scheduler.c.
void syx_scheduler_poll_register_source (SyxSchedulerSourceFunc callback, SyxOop semaphore)
The scheduler runs the callback to check whether the source is ready then signal the semaphore. To tell that the source is ready, return TRUE from the callback, otherwise FALSE.
Parameters:
callback the callback to call for each scheduler iteration
semaphore the semaphore to signal when the source is ready
Definition at line 166 of file syx-scheduler.c.
void syx_scheduler_poll_unregister_source (SyxSchedulerSourceFunc callback, SyxOop semaphore)
Remove an idle source previously added with syx_scheduler_poll_register_source
Definition at line 179 of file syx-scheduler.c.
void syx_scheduler_quit (void)
Stop the scheduler
Definition at line 200 of file syx-scheduler.c.
Referenced by syx_quit().
syx_bool syx_scheduler_remove_process (SyxOop process)
Remove a Process from being scheduled.
Parameters:
process a valid Process
Returns:
TRUE if the given Process has been found and removed successfully, FALSE otherwise
Definition at line 229 of file syx-scheduler.c.
Referenced by syx_initialize_system(), syx_interp_leave_and_answer(), and syx_process_execute_blocking().
void syx_scheduler_run (void)
Run the scheduler in blocking mode. Exits once no Process is scheduled
Definition at line 132 of file syx-scheduler.c.
Variable Documentation
SyxOop syx_processor
Definition at line 41 of file syx-scheduler.c.
Referenced by syx_scheduler_init().
Documented by Luca Bruno and ScaccoMatto