Syx: syx/syx-parser.h File Reference
syx-parser.h File Reference
#include "syx-types.h"
#include "syx-object.h"
#include "syx-lexer.h"
#include "syx-bytecode.h"
Data Structures
struct SyxParserScope
struct SyxParser
Defines
#define SYX_PARSER_MAX_NAMES 0xFF
#define SYX_PARSER_MAX_SCOPES 0xFF
#define SYX_PARSER_MAX_CASCADES 0xFF
Typedefs
typedef struct SyxParserScope SyxParserScope
typedef struct SyxParser SyxParser
Functions
EXPORT SyxParser * syx_parser_new (SyxLexer *lexer, SyxOop method, SyxOop klass)
EXPORT void syx_parser_free (SyxParser *parser, syx_bool free_segment)
EXPORT syx_bool syx_parser_parse (SyxParser *parser, syx_bool skip_message_pattern)
Define Documentation
#define SYX_PARSER_MAX_CASCADES 0xFF
Definition at line 37 of file syx-parser.h.
#define SYX_PARSER_MAX_NAMES 0xFF
Definition at line 35 of file syx-parser.h.
#define SYX_PARSER_MAX_SCOPES 0xFF
Definition at line 36 of file syx-parser.h.
Typedef Documentation
typedef struct SyxParser SyxParser
Definition at line 46 of file syx-parser.h.
typedef struct SyxParserScope SyxParserScope
Definition at line 39 of file syx-parser.h.
Function Documentation
EXPORT void syx_parser_free (SyxParser * self, syx_bool free_segment)
Free all memory used by the parser.
Parameters:
free_segment TRUE frees the instance_names (not its contents) and the lexer
Definition at line 121 of file syx-parser.c.
Referenced by syx_cold_parse_methods().
EXPORT SyxParser* syx_parser_new (SyxLexer * lexer, SyxOop method, SyxOop klass)
Create a new SyxParser to parse the code later.
Parameters:
method a CompiledMethod or CompiledBlock
instance_names list of instance variable names
Definition at line 71 of file syx-parser.c.
Referenced by syx_cold_parse_methods().
EXPORT syx_bool syx_parser_parse (SyxParser * self, syx_bool skip_message_pattern)
Do parse.
Returns:
TRUE if parsing was successful, otherwise FALSE
Definition at line 141 of file syx-parser.c.
Referenced by syx_cold_parse_methods().
Documented by Luca Bruno and ScaccoMatto