Syx: syx/syx-bytecode.c File Reference
syx-bytecode.c File Reference
#include "syx-memory.h"
#include "syx-platform.h"
#include "syx-types.h"
#include "syx-object.h"
#include "syx-bytecode.h"
Functions
SyxBytecode * syx_bytecode_new (void)
void syx_bytecode_gen_instruction (SyxBytecode *bytecode, syx_uint8 high, syx_uint16 low)
void syx_bytecode_gen_message (SyxBytecode *bytecode, syx_bool to_super, syx_uint32 argument_count, syx_symbol selector)
syx_uint32 syx_bytecode_gen_literal (SyxBytecode *bytecode, SyxOop literal)
Variables
syx_symbol syx_bytecode_unary_messages []
syx_symbol syx_bytecode_binary_messages []
Function Documentation
void syx_bytecode_gen_instruction (SyxBytecode * bytecode, syx_uint8 high, syx_uint16 low)
Manually generate an instruction.
This function creates an instruction and insert it into the code array. If the low argument is higher than the max value, then generate a SYX_BYTECODE_EXTENDED instruction with the command as argument. The low argument is put to the next code slot.
Look at SYX_BYTECODE_ARGUMENT_BITS and SYX_BYTECODE_ARGUMENT_MAX for more informations.
Parameters:
high a SyxBytecodeCommand value
low an arbitrary number identifying an argument
Definition at line 76 of file syx-bytecode.c.
Referenced by syx_bytecode_gen_instruction(), and syx_bytecode_gen_message().
syx_uint32 syx_bytecode_gen_literal (SyxBytecode * bytecode, SyxOop literal)
Generate a literal.
Insert the given literal into the literals array if it's not already there.
Parameters:
literal an object
Returns:
The position of literal into the literals array
Definition at line 156 of file syx-bytecode.c.
Referenced by syx_bytecode_gen_message().
void syx_bytecode_gen_message (SyxBytecode * bytecode, syx_bool to_super, syx_uint32 argument_count, syx_symbol selector)
Generate a message instruction.
If the message shouldn't be sent to super and the selector is known to be a common unary or binary message, send SYX_BYTECODE_SEND_UNARY or SYX_BYTECODE_SEND_BINARY with its relative index into syx_bytecode_unary_messages or syx_bytecode_binary_messages.
If it's a non-specific message, then specify the number of arguments with the SYX_BYTECODE_MARK_ARGUMENTS instruction and generate a SYX_BYTECODE_SEND_MESSAGE or SYX_BYTECODE_SEND_SUPER instruction.
Parameters:
to_super TRUE if the message must be sent to the superclass
argument_count the number of arguments the message requires
selector a message pattern
Definition at line 100 of file syx-bytecode.c.
SyxBytecode* syx_bytecode_new (void)
Creates a new bytecode holder.
Returns:
A SyxBytecode instance
Definition at line 37 of file syx-bytecode.c.
Referenced by syx_parser_new().
Variable Documentation
syx_symbol syx_bytecode_binary_messages[]
Initial value:
 {"+", "-", "<", ">", "<=", ">=", "=", "~=", "at:",
                                             "do:", "value:", "valueWithArguments:",
                                             "new:", "to:", "basicAt:", NULL}
Same as syx_bytecode_unary_messages but contains binary messages and keyword messages with a single argument
Definition at line 58 of file syx-bytecode.c.
syx_symbol syx_bytecode_unary_messages[]
Initial value:
 {"isNil", "notNil", "value", "new", "class", "superclass",
                                            "print", "printNl", "printString", "unity", NULL}
Contains common unary messages avoiding them to be inserted into method literals.
Definition at line 52 of file syx-bytecode.c.
Documented by Luca Bruno and ScaccoMatto