Syx: syx/syx-parser.c File Reference
syx-parser.c File Reference
#include "syx-object.h"
#include <assert.h>
#include <string.h>
#include "syx-error.h"
#include "syx-types.h"
#include "syx-memory.h"
#include "syx-bytecode.h"
#include "syx-parser.h"
#include "syx-interp.h"
#include "syx-utils.h"
Functions
SyxParser * syx_parser_new (SyxLexer *lexer, SyxOop method, SyxOop klass)
void syx_parser_free (SyxParser *self, syx_bool free_segment)
syx_bool syx_parser_parse (SyxParser *self, syx_bool skip_message_pattern)
Function Documentation
void syx_parser_free (SyxParser * self, syx_bool free_segment)
Free all memory used by the parser.
Parameters:
free_segment TRUE frees the instance_names (not its contents) and the lexer
Definition at line 121 of file syx-parser.c.
Referenced by syx_cold_parse_methods().
SyxParser* syx_parser_new (SyxLexer * lexer, SyxOop method, SyxOop klass)
Create a new SyxParser to parse the code later.
Parameters:
method a CompiledMethod or CompiledBlock
instance_names list of instance variable names
Definition at line 71 of file syx-parser.c.
Referenced by syx_cold_parse_methods().
syx_bool syx_parser_parse (SyxParser * self, syx_bool skip_message_pattern)
Do parse.
Returns:
TRUE if parsing was successful, otherwise FALSE
Definition at line 141 of file syx-parser.c.
Referenced by syx_cold_parse_methods().
Documented by Luca Bruno and ScaccoMatto