Syx: syx/syx-bytecode.h File Reference
syx-bytecode.h File Reference
#include "syx-types.h"
#include "syx-object.h"
#include "syx-memory.h"
Data Structures
struct SyxBytecode
Defines
#define SYX_BYTECODE_BITS 16
#define SYX_BYTECODE_MAX ((1 << SYX_BYTECODE_BITS) - 1)
#define SYX_BYTECODE_COMMAND_BITS 5
#define SYX_BYTECODE_COMMAND_MAX ((1 << SYX_BYTECODE_COMMAND_BITS) - 1)
#define SYX_BYTECODE_COMMAND_MASK (SYX_BYTECODE_COMMAND_MAX << (SYX_BYTECODE_BITS - SYX_BYTECODE_COMMAND_BITS))
#define SYX_BYTECODE_ARGUMENT_BITS (SYX_BYTECODE_BITS - SYX_BYTECODE_COMMAND_BITS)
#define SYX_BYTECODE_ARGUMENT_MAX ((1 << SYX_BYTECODE_ARGUMENT_BITS) - 1)
#define SYX_BYTECODE_ARGUMENT_MASK (SYX_BYTECODE_ARGUMENT_MAX)
#define SYX_FUNC_BYTECODE(name, arg) INLINE void syx_bytecode_ ## name (SyxBytecode *bytecode, arg)
Typedefs
typedef struct SyxBytecode SyxBytecode
Functions
EXPORT SyxBytecode * syx_bytecode_new (void)
INLINE void syx_bytecode_free (SyxBytecode *bytecode)
EXPORT void syx_bytecode_gen_instruction (SyxBytecode *bytecode, syx_uint8 high, syx_uint16 low)
EXPORT void syx_bytecode_gen_message (SyxBytecode *bytecode, syx_bool to_super, syx_uint32 argument_count, syx_symbol selector)
EXPORT syx_uint32 syx_bytecode_gen_literal (SyxBytecode *bytecode, SyxOop literal)
Variables
syx_symbol syx_bytecode_unary_messages []
syx_symbol syx_bytecode_binary_messages []
Define Documentation
#define SYX_BYTECODE_ARGUMENT_BITS (SYX_BYTECODE_BITS - SYX_BYTECODE_COMMAND_BITS)
Bits used to represent an argument into a bytecode
Definition at line 55 of file syx-bytecode.h.
Referenced by syx_bytecode_gen_instruction().
#define SYX_BYTECODE_ARGUMENT_MASK (SYX_BYTECODE_ARGUMENT_MAX)
A mask to be used with bit-wise AND to retrieve the command from a bytecode
Definition at line 59 of file syx-bytecode.h.
#define SYX_BYTECODE_ARGUMENT_MAX ((1 << SYX_BYTECODE_ARGUMENT_BITS) - 1)
Max value of an argument
Definition at line 57 of file syx-bytecode.h.
Referenced by syx_bytecode_gen_instruction().
#define SYX_BYTECODE_BITS 16
Number of bits used for a bytecode
Definition at line 42 of file syx-bytecode.h.
#define SYX_BYTECODE_COMMAND_BITS 5
Bits used to represent a command into a bytecode
Definition at line 48 of file syx-bytecode.h.
#define SYX_BYTECODE_COMMAND_MASK (SYX_BYTECODE_COMMAND_MAX << (SYX_BYTECODE_BITS - SYX_BYTECODE_COMMAND_BITS))
A mask to be used with bit-wise AND to retrieve the command from a bytecode
Definition at line 52 of file syx-bytecode.h.
#define SYX_BYTECODE_COMMAND_MAX ((1 << SYX_BYTECODE_COMMAND_BITS) - 1)
Max number of commands
Definition at line 50 of file syx-bytecode.h.
#define SYX_BYTECODE_MAX ((1 << SYX_BYTECODE_BITS) - 1)
The total length of an instruction
Definition at line 45 of file syx-bytecode.h.
#define SYX_FUNC_BYTECODE (name, arg) INLINE void syx_bytecode_ ## name (SyxBytecode *bytecode, arg)
Definition at line 64 of file syx-bytecode.h.
Typedef Documentation
typedef struct SyxBytecode SyxBytecode
Definition at line 67 of file syx-bytecode.h.
Function Documentation
INLINE void syx_bytecode_free (SyxBytecode * bytecode)
Frees the memory allocated for a SyxBytecode by syx_bytecode_new.
Parameters:
bytecode the SyxBytecode to be freed
Definition at line 90 of file syx-bytecode.h.
Referenced by syx_parser_free().
EXPORT void syx_bytecode_gen_instruction (SyxBytecode * bytecode, syx_uint8 high, syx_uint16 low)
Manually generate an instruction.
This function creates an instruction and insert it into the code array. If the low argument is higher than the max value, then generate a SYX_BYTECODE_EXTENDED instruction with the command as argument. The low argument is put to the next code slot.
Look at SYX_BYTECODE_ARGUMENT_BITS and SYX_BYTECODE_ARGUMENT_MAX for more informations.
Parameters:
high a SyxBytecodeCommand value
low an arbitrary number identifying an argument
Definition at line 76 of file syx-bytecode.c.
Referenced by syx_bytecode_gen_instruction(), and syx_bytecode_gen_message().
EXPORT syx_uint32 syx_bytecode_gen_literal (SyxBytecode * bytecode, SyxOop literal)
Generate a literal.
Insert the given literal into the literals array if it's not already there.
Parameters:
literal an object
Returns:
The position of literal into the literals array
Definition at line 156 of file syx-bytecode.c.
Referenced by syx_bytecode_gen_message().
EXPORT void syx_bytecode_gen_message (SyxBytecode * bytecode, syx_bool to_super, syx_uint32 argument_count, syx_symbol selector)
Generate a message instruction.
If the message shouldn't be sent to super and the selector is known to be a common unary or binary message, send SYX_BYTECODE_SEND_UNARY or SYX_BYTECODE_SEND_BINARY with its relative index into syx_bytecode_unary_messages or syx_bytecode_binary_messages.
If it's a non-specific message, then specify the number of arguments with the SYX_BYTECODE_MARK_ARGUMENTS instruction and generate a SYX_BYTECODE_SEND_MESSAGE or SYX_BYTECODE_SEND_SUPER instruction.
Parameters:
to_super TRUE if the message must be sent to the superclass
argument_count the number of arguments the message requires
selector a message pattern
Definition at line 100 of file syx-bytecode.c.
EXPORT SyxBytecode* syx_bytecode_new (void)
Creates a new bytecode holder.
Returns:
A SyxBytecode instance
Definition at line 37 of file syx-bytecode.c.
Referenced by syx_parser_new().
Variable Documentation
syx_symbol syx_bytecode_binary_messages[]
Same as syx_bytecode_unary_messages but contains binary messages and keyword messages with a single argument
Definition at line 58 of file syx-bytecode.c.
syx_symbol syx_bytecode_unary_messages[]
Contains common unary messages avoiding them to be inserted into method literals.
Definition at line 52 of file syx-bytecode.c.
Documented by Luca Bruno and ScaccoMatto