Syx: syx/syx-scheduler.h File Reference
syx-scheduler.h File Reference
#include "syx-platform.h"
#include "syx-types.h"
#include "syx-object.h"
#include <stdio.h>
Data Structures
struct SyxSchedulerPoll
Defines
#define syx_processor_byteslice (*_syx_processor_byteslice)
#define syx_processor_active_process (*_syx_processor_active_process)
Typedefs
typedef struct SyxSchedulerPoll SyxSchedulerPoll
typedef syx_bool(* SyxSchedulerSourceFunc)(void)
Functions
EXPORT void syx_scheduler_init (void)
EXPORT syx_bool syx_scheduler_iterate (void)
EXPORT void syx_scheduler_run (void)
EXPORT void syx_scheduler_quit (void)
EXPORT syx_bool syx_scheduler_add_process (SyxOop process)
EXPORT syx_bool syx_scheduler_remove_process (SyxOop process)
EXPORT void syx_scheduler_poll_read_register (syx_nint fd, SyxOop semaphore)
EXPORT void syx_scheduler_poll_write_register (syx_nint fd, SyxOop semaphore)
EXPORT void syx_scheduler_poll_register_source (SyxSchedulerSourceFunc callback, SyxOop semaphore)
EXPORT void syx_scheduler_poll_unregister_source (SyxSchedulerSourceFunc callback, SyxOop semaphore)
Variables
SYX_BEGIN_DECLS EXPORT SyxOop syx_processor
Define Documentation
#define syx_processor_active_process (*_syx_processor_active_process)
Get the active process running on
Definition at line 72 of file syx-scheduler.h.
Referenced by syx_interp_leave_and_answer(), syx_memory_save_image(), syx_process_execute_blocking(), syx_scheduler_add_process(), syx_scheduler_iterate(), syx_scheduler_remove_process(), syx_scheduler_run(), syx_semaphore_wait(), syx_show_traceback(), syx_signal(), and syx_signal_does_not_understand().
#define syx_processor_byteslice (*_syx_processor_byteslice)
Get the byteslice
Definition at line 69 of file syx-scheduler.h.
Typedef Documentation
typedef struct SyxSchedulerPoll SyxSchedulerPoll
Definition at line 41 of file syx-scheduler.h.
typedef syx_bool(* SyxSchedulerSourceFunc)(void)
Definition at line 53 of file syx-scheduler.h.
Function Documentation
EXPORT syx_bool syx_scheduler_add_process (SyxOop process)
Add a Process to be scheduled.
Parameters:
process a valid Process
Returns:
TRUE if the given Process has been scheduled successfully, FALSE otherwise
Definition at line 209 of file syx-scheduler.c.
Referenced by syx_process_new().
EXPORT void syx_scheduler_init (void)
Initialize the scheduler.
If absent, create a ProcessorScheduler instance named Processor and insert it into the Smalltalk dictionary.
Definition at line 97 of file syx-scheduler.c.
Referenced by syx_fetch_basic().
EXPORT syx_bool syx_scheduler_iterate (void)
Do a single iteration of the scheduler. Returns FALSE when no pending processes are left.
Definition at line 118 of file syx-scheduler.c.
EXPORT void syx_scheduler_poll_read_register (syx_nint fd, SyxOop semaphore)
Watch a file descriptor for writing
Parameters:
fd the file descriptor
semaphore to signal when fd is ready for reading
Watch a file descriptor for writing
Parameters:
fd the HANDLE
semaphore to signal when fd is ready for reading
Definition at line 150 of file syx-scheduler-posix.c.
EXPORT void syx_scheduler_poll_register_source (SyxSchedulerSourceFunc callback, SyxOop semaphore)
The scheduler runs the callback to check whether the source is ready then signal the semaphore. To tell that the source is ready, return TRUE from the callback, otherwise FALSE.
Parameters:
callback the callback to call for each scheduler iteration
semaphore the semaphore to signal when the source is ready
Definition at line 166 of file syx-scheduler.c.
EXPORT void syx_scheduler_poll_unregister_source (SyxSchedulerSourceFunc callback, SyxOop semaphore)
Remove an idle source previously added with syx_scheduler_poll_register_source
Definition at line 179 of file syx-scheduler.c.
EXPORT void syx_scheduler_poll_write_register (syx_nint fd, SyxOop semaphore)
Watch a file descriptor for writing
Parameters:
fd the file descriptor
semaphore to signal when fd is ready for writing
Watch a file descriptor for writing
Parameters:
fd the HANDLE
semaphore to signal when fd is ready for writing
Definition at line 172 of file syx-scheduler-posix.c.
EXPORT void syx_scheduler_quit (void)
Stop the scheduler
Definition at line 200 of file syx-scheduler.c.
Referenced by syx_quit().
EXPORT syx_bool syx_scheduler_remove_process (SyxOop process)
Remove a Process from being scheduled.
Parameters:
process a valid Process
Returns:
TRUE if the given Process has been found and removed successfully, FALSE otherwise
Definition at line 229 of file syx-scheduler.c.
Referenced by syx_initialize_system(), syx_interp_leave_and_answer(), and syx_process_execute_blocking().
EXPORT void syx_scheduler_run (void)
Run the scheduler in blocking mode. Exits once no Process is scheduled
Definition at line 132 of file syx-scheduler.c.
Variable Documentation
SYX_BEGIN_DECLS EXPORT SyxOop syx_processor
Definition at line 41 of file syx-scheduler.c.
Referenced by syx_scheduler_init().
Documented by Luca Bruno and ScaccoMatto