Syx: syx/syx-lexer.c File Reference
syx-lexer.c File Reference
#include "syx-memory.h"
#include "syx-platform.h"
#include "syx-error.h"
#include "syx-types.h"
#include "syx-lexer.h"
#include <ctype.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <gmp.h>
Functions
SyxLexer * syx_lexer_new (syx_symbol text)
void syx_lexer_free (SyxLexer *lexer, syx_bool free_text)
void syx_token_free (SyxToken token)
syx_char syx_lexer_forward (SyxLexer *lexer)
SyxToken syx_lexer_next_token (SyxLexer *lexer)
syx_string syx_lexer_next_chunk (SyxLexer *lexer)
SyxToken syx_lexer_get_last_token (SyxLexer *lexer)
syx_char syx_lexer_get_last_char (SyxLexer *lexer)
Function Documentation
syx_char syx_lexer_forward (SyxLexer * lexer)
Get the next character or 0
Definition at line 419 of file syx-lexer.c.
Referenced by syx_lexer_next_token().
void syx_lexer_free (SyxLexer * lexer, syx_bool free_text)
Frees the memory allocated by syx_lexer_new.
Parameters:
free_text TRUE frees the text
Definition at line 86 of file syx-lexer.c.
Referenced by syx_cold_file_in(), and syx_parser_free().
syx_char syx_lexer_get_last_char (SyxLexer * lexer)
Returns the last character returned by syx_lexer_forward
Definition at line 555 of file syx-lexer.c.
Referenced by syx_lexer_push_back().
SyxToken syx_lexer_get_last_token (SyxLexer * lexer)
Returns the last token returned by syx_lexer_next_token
Definition at line 548 of file syx-lexer.c.
SyxLexer* syx_lexer_new (syx_symbol text)
Creates a new lexer to parse the code.
Parameters:
text the code
Returns:
A new SyxLexer
Definition at line 65 of file syx-lexer.c.
Referenced by syx_cold_file_in(), and syx_cold_parse_methods().
syx_string syx_lexer_next_chunk (SyxLexer * lexer)
Get the next chunk of code separated ending with an exlamation mark (!).
Returns:
A string containing the chunk without the exlamation mark. It must be freed once it's not needed anymore
Definition at line 513 of file syx-lexer.c.
Referenced by syx_cold_parse_methods().
SyxToken syx_lexer_next_token (SyxLexer * lexer)
Returns the next token parsed by the lexer
Definition at line 439 of file syx-lexer.c.
Referenced by syx_cold_parse(), syx_cold_parse_methods(), syx_lexer_next_chunk(), and syx_parser_parse().
void syx_token_free (SyxToken token)
Frees the memory allocated for a SyxToken.
The only way the token can be freed is only when it holds a string. In that case, the string is freed
Definition at line 101 of file syx-lexer.c.
Referenced by syx_cold_parse(), syx_cold_parse_methods(), and syx_lexer_next_chunk().
Documented by Luca Bruno and ScaccoMatto