Syx: syx/syx-utils.c File Reference
syx-utils.c File Reference
#include "syx-memory.h"
#include "syx-platform.h"
#include "syx-types.h"
#include "syx-object.h"
#include "syx-init.h"
#include "syx-scheduler.h"
#include "syx-error.h"
#include "syx-utils.h"
#include "syx-parser.h"
#include "syx-interp.h"
#include "syx-lexer.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <ctype.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <stdarg.h>
#include <dlfcn.h>
Functions
syx_bool syx_cold_parse_methods (SyxLexer *lexer)
syx_bool syx_cold_parse (SyxLexer *lexer)
syx_bool syx_cold_file_in (syx_symbol filename)
SyxOop syx_send_unary_message (SyxOop receiver, syx_symbol selector)
SyxOop syx_send_binary_message (SyxOop receiver, syx_symbol selector, SyxOop argument)
SyxOop syx_send_message (SyxOop receiver, syx_symbol selector, syx_varsize num_args,...)
SyxOop syx_vsend_message (SyxOop receiver, syx_symbol selector, syx_int32 num_args, va_list ap)
SyxOop syx_file_in_blocking (syx_symbol file)
SyxOop syx_do_it_blocking (syx_symbol code)
syx_wstring syx_to_wstring (syx_symbol s)
syx_string syx_to_string (syx_wsymbol ws)
syx_uint32 syx_find_first_non_whitespace (syx_symbol string)
void syx_show_traceback (void)
Function Documentation
syx_bool syx_cold_file_in (syx_symbol filename)
Parse a declaration file.
Returns:
TRUE if no error has occurred
Definition at line 383 of file syx-utils.c.
syx_bool syx_cold_parse (SyxLexer * lexer)
Parse simple declarations like classes and methods.
Returns:
TRUE if no error has occurred
Definition at line 356 of file syx-utils.c.
Referenced by syx_cold_file_in().
syx_bool syx_cold_parse_methods (SyxLexer * lexer)
Definition at line 269 of file syx-utils.c.
Referenced by syx_cold_parse().
SyxOop syx_do_it_blocking (syx_symbol code)
Do it in blocking mode. This function send a message to String>>doIt.
Returns:
Return the last returned object from the process
Definition at line 560 of file syx-utils.c.
SyxOop syx_file_in_blocking (syx_symbol file)
Files in a file in blocking mode. This function send a message to FileStream>>fileIn:.
Returns:
Return the last returned object from the process
Definition at line 539 of file syx-utils.c.
syx_uint32 syx_find_first_non_whitespace (syx_symbol string)
Returns the first index in the string that is not a whitespace
Definition at line 595 of file syx-utils.c.
Referenced by syx_parser_parse().
SyxOop syx_send_binary_message (SyxOop receiver, syx_symbol selector, SyxOop argument)
Create a MethodContext for a binary message ready to enter a Process
Definition at line 457 of file syx-utils.c.
Referenced by syx_file_in_blocking(), syx_initialize_system(), syx_signal(), syx_signal_create_context(), and syx_signal_does_not_understand().
SyxOop syx_send_message (SyxOop receiver, syx_symbol selector, syx_varsize num_args, ...)
Create a MethodContext for an arbitrary message ready to enter a Process.
Parameters:
num_args number of variadic SyxOop arguments
Definition at line 484 of file syx-utils.c.
SyxOop syx_send_unary_message (SyxOop receiver, syx_symbol selector)
Create a MethodContext for a unary message ready to enter a Process
Definition at line 436 of file syx-utils.c.
Referenced by syx_build_basic(), syx_do_it_blocking(), syx_memory_clear(), syx_object_free(), syx_object_initialize(), syx_signal(), syx_signal_create_context(), and syx_vsend_message().
void syx_show_traceback (void)
Print to stdout the current execution state of the interpreter and the Process traceback
Definition at line 609 of file syx-utils.c.
syx_string syx_to_string (syx_wsymbol ws)
Returns a syx_string from a syx_wstring
Definition at line 585 of file syx-utils.c.
syx_wstring syx_to_wstring (syx_symbol s)
Returns a syx_wstring from a syx_string
Definition at line 575 of file syx-utils.c.
SyxOop syx_vsend_message (SyxOop receiver, syx_symbol selector, syx_int32 num_args, va_list ap)
Create a MethodContext for an arbitrary message ready to enter a Process.
Parameters:
num_args the number of arguments
ap a va_list containing all SyxOops
Definition at line 504 of file syx-utils.c.
Referenced by syx_send_message().
Documented by Luca Bruno and ScaccoMatto