Syx: syx/syx-utils.h File Reference
syx-utils.h File Reference
#include "syx-platform.h"
#include <stdarg.h>
#include "syx-types.h"
#include "syx-lexer.h"
Defines
#define SYX_IFDEF_UNICODE(s) s
#define SYX_IFDEF_ANSI(ws) ws
#define SYX_IFDEF_CHAR_T syx_char
#define SYX_VSPRINTF(fmt, var)
Functions
SYX_BEGIN_DECLS EXPORT syx_bool syx_cold_parse (SyxLexer *lexer)
EXPORT syx_bool syx_cold_parse_methods (SyxLexer *lexer)
EXPORT syx_bool syx_cold_file_in (syx_symbol filename)
EXPORT void syx_semaphore_signal (SyxOop semaphore)
EXPORT void syx_semaphore_wait (SyxOop semaphore)
EXPORT SyxOop syx_send_unary_message (SyxOop receiver, syx_symbol selector)
EXPORT SyxOop syx_send_binary_message (SyxOop receiver, syx_symbol selector, SyxOop argument)
EXPORT SyxOop syx_send_message (SyxOop receiver, syx_symbol selector, syx_varsize num_args,...)
EXPORT SyxOop syx_vsend_message (SyxOop receiver, syx_symbol selector, syx_varsize num_args, va_list ap)
EXPORT SyxOop syx_file_in_blocking (syx_symbol file)
EXPORT SyxOop syx_do_it_blocking (syx_symbol code)
EXPORT void syx_show_traceback (void)
EXPORT syx_wstring syx_to_wstring (syx_symbol s)
EXPORT syx_string syx_to_string (syx_wsymbol ws)
EXPORT syx_uint32 syx_find_first_non_whitespace (syx_symbol string)
Define Documentation
#define SYX_IFDEF_ANSI (ws) ws
If UNICODE is defined, convert the given wide string (syx_wchar) to an ANSI string (syx_char)
Definition at line 80 of file syx-utils.h.
#define SYX_IFDEF_CHAR_T syx_char
If UNICODE is defined, expand to syx_wchar, else syx_char
Definition at line 82 of file syx-utils.h.
#define SYX_IFDEF_UNICODE (s) s
If UNICODE is defined, convert the given ANSI string (syx_char) to a wide string (syx_wchar)
Definition at line 78 of file syx-utils.h.
Referenced by syx_library_open(), and syx_library_symbol().
#define SYX_VSPRINTF (fmt, var)
Value:
{                                             \
    syx_int32 n;                                \
    va_list ap;                                 \
    syx_int32 size;                             \
    syx_string s;                               \
                                                \
    var = NULL;                                 \
    if (fmt)                                    \
      {                                         \
        size = 100;                             \
        s = NULL;                               \
        while (TRUE)                            \
          {                                     \
            s = syx_realloc(s, size);           \
            va_start(ap, fmt);                  \
            n = vsnprintf (s, size, fmt, ap);   \
            va_end(ap);                         \
            if (n > -1 && n < size)             \
              {                                 \
                var = s;                        \
                break;                          \
              }                                 \
                                                \
            size *= 2;                          \
          }                                     \
      }                                         \
  }                                             \
Definition at line 86 of file syx-utils.h.
Referenced by syx_string_new().
Function Documentation
EXPORT syx_bool syx_cold_file_in (syx_symbol filename)
Parse a declaration file.
Returns:
TRUE if no error has occurred
Definition at line 383 of file syx-utils.c.
SYX_BEGIN_DECLS EXPORT syx_bool syx_cold_parse (SyxLexer * lexer)
Parse simple declarations like classes and methods.
Returns:
TRUE if no error has occurred
Definition at line 356 of file syx-utils.c.
Referenced by syx_cold_file_in().
EXPORT syx_bool syx_cold_parse_methods (SyxLexer * lexer)
Definition at line 269 of file syx-utils.c.
Referenced by syx_cold_parse().
EXPORT SyxOop syx_do_it_blocking (syx_symbol code)
Do it in blocking mode. This function send a message to String>>doIt.
Returns:
Return the last returned object from the process
Definition at line 560 of file syx-utils.c.
EXPORT SyxOop syx_file_in_blocking (syx_symbol file)
Files in a file in blocking mode. This function send a message to FileStream>>fileIn:.
Returns:
Return the last returned object from the process
Definition at line 539 of file syx-utils.c.
EXPORT syx_uint32 syx_find_first_non_whitespace (syx_symbol string)
Returns the first index in the string that is not a whitespace
Definition at line 595 of file syx-utils.c.
Referenced by syx_parser_parse().
EXPORT void syx_semaphore_signal (SyxOop semaphore)
Send a signal to a Semaphore to wake up waiting processes.
The function is thread-safe
Definition at line 954 of file syx-object.c.
EXPORT void syx_semaphore_wait (SyxOop semaphore)
Put the active process in waiting state until semaphore is signaled.
The function is thread-safe
Definition at line 990 of file syx-object.c.
EXPORT SyxOop syx_send_binary_message (SyxOop receiver, syx_symbol selector, SyxOop argument)
Create a MethodContext for a binary message ready to enter a Process
Definition at line 457 of file syx-utils.c.
Referenced by syx_file_in_blocking(), syx_initialize_system(), syx_signal(), syx_signal_create_context(), and syx_signal_does_not_understand().
EXPORT SyxOop syx_send_message (SyxOop receiver, syx_symbol selector, syx_varsize num_args, ...)
Create a MethodContext for an arbitrary message ready to enter a Process.
Parameters:
num_args number of variadic SyxOop arguments
Definition at line 484 of file syx-utils.c.
EXPORT SyxOop syx_send_unary_message (SyxOop receiver, syx_symbol selector)
Create a MethodContext for a unary message ready to enter a Process
Definition at line 436 of file syx-utils.c.
Referenced by syx_build_basic(), syx_do_it_blocking(), syx_memory_clear(), syx_object_free(), syx_object_initialize(), syx_signal(), syx_signal_create_context(), and syx_vsend_message().
EXPORT void syx_show_traceback (void)
Print to stdout the current execution state of the interpreter and the Process traceback
Definition at line 609 of file syx-utils.c.
EXPORT syx_string syx_to_string (syx_wsymbol ws)
Returns a syx_string from a syx_wstring
Definition at line 585 of file syx-utils.c.
EXPORT syx_wstring syx_to_wstring (syx_symbol s)
Returns a syx_wstring from a syx_string
Definition at line 575 of file syx-utils.c.
EXPORT SyxOop syx_vsend_message (SyxOop receiver, syx_symbol selector, syx_varsize num_args, va_list ap)
Documented by Luca Bruno and ScaccoMatto