Syx: syx/syx-interp.c File Reference
syx-interp.c File Reference
#include "syx-object.h"
#include "syx-interp.h"
#include "syx-utils.h"
#include "syx-scheduler.h"
#include "syx-init.h"
#include "syx-plugins.h"
#include "syx-memory.h"
#include "syx-bytecode.h"
#include "syx-error.h"
#include "syx-profile.h"
#include <assert.h>
Functions
SyxInterpFrame * syx_interp_context_to_frame (SyxOop context)
SyxOop syx_interp_frame_to_context (SyxOop stack, SyxInterpFrame *frame)
void syx_interp_init (void)
void syx_interp_quit (void)
syx_bool syx_interp_swap_context (SyxOop process, SyxOop context)
syx_bool syx_interp_enter_context (SyxOop process, SyxOop context)
syx_bool syx_interp_leave_and_answer (SyxOop return_object, syx_bool use_stack_return)
void syx_process_execute_scheduled (SyxOop process)
void syx_process_execute_blocking (SyxOop process)
Function Documentation
SyxInterpFrame* syx_interp_context_to_frame (SyxOop context)
Returns the frame associated to the given context
Definition at line 165 of file syx-interp.c.
Referenced by syx_interp_swap_context().
syx_bool syx_interp_enter_context (SyxOop process, SyxOop context)
Enters a new MethodContext or BlockContext.
Returns:
FALSE if the context was syx_nil
Definition at line 271 of file syx-interp.c.
Referenced by syx_build_basic(), syx_do_it_blocking(), syx_file_in_blocking(), syx_initialize_system(), syx_memory_clear(), syx_object_free(), syx_object_initialize(), syx_signal(), and syx_signal_does_not_understand().
SyxOop syx_interp_frame_to_context (SyxOop stack, SyxInterpFrame * frame)
Creates a MethodContext or BlockContext from a frame
Parameters:
stack the OOP of the whole stack, e.g. SYX_PROCESS_STACK (aProcess). This will not be used if the frame has been detached.
Returns:
a new context
Definition at line 179 of file syx-interp.c.
void syx_interp_init (void)
Initialize the interpreter to be ready to execute processes.
This function is called internally by Syx and should not be called from user applications.
Definition at line 219 of file syx-interp.c.
Referenced by syx_fetch_basic().
syx_bool syx_interp_leave_and_answer (SyxOop return_object, syx_bool use_stack_return)
Leaves the current frame and push an object into the returning context.
Use the stack return frame use_stack_return is specified, otherwise use the parent frame. Then sets the returned object variable of the process to the specified object. Finally swap the context with the new one. Terminate the process if no valid return frame is found.
Parameters:
return_object the object to be pushed into the returning context
use_stack_return TRUE to use the stack return frame, FALSE to use the parent frame
Returns:
FALSE if no valid return frame is found
Definition at line 334 of file syx-interp.c.
void syx_interp_quit (void)
Finalize the execution of processes and free all the memory used by the interpreter.
This function is called internally by Syx e should not be called from user applications
Definition at line 229 of file syx-interp.c.
Referenced by syx_quit().
syx_bool syx_interp_swap_context (SyxOop process, SyxOop context)
Swap the current context with the given one. The context must be already existing in the process stack.
Returns:
FALSE if the context was syx_nil
Definition at line 240 of file syx-interp.c.
void syx_process_execute_blocking (SyxOop process)
Same as syx_process_execute_scheduled but does not take care about the byteslice counter, and control is not yield until the process is terminated.
Definition at line 390 of file syx-interp.c.
Referenced by syx_build_basic(), syx_do_it_blocking(), syx_file_in_blocking(), syx_initialize_system(), syx_memory_clear(), syx_object_free(), syx_object_initialize(), and syx_signal().
void syx_process_execute_scheduled (SyxOop process)
Executes the given process and returns once the byteslice is reached, no more instructions left or yield has been requested.
Parameters:
process must not be nil
Definition at line 368 of file syx-interp.c.
Referenced by syx_scheduler_iterate(), and syx_scheduler_run().
Documented by Luca Bruno and ScaccoMatto