Syx: syx/syx-lexer.h File Reference
syx-lexer.h File Reference
#include "syx-platform.h"
#include "syx-types.h"
#include "syx-enums.h"
#include <gmp.h>
Data Structures
struct SyxToken
union SyxToken::SyxTokenValue
struct SyxLexer
Typedefs
typedef typedefSYX_BEGIN_DECLS
struct SyxToken SyxToken
typedef struct SyxLexer SyxLexer
Functions
EXPORT void syx_token_free (SyxToken token)
EXPORT SyxLexer * syx_lexer_new (syx_symbol text)
EXPORT void syx_lexer_free (SyxLexer *lexer, syx_bool free_text)
EXPORT syx_char syx_lexer_forward (SyxLexer *lexer)
EXPORT SyxToken syx_lexer_next_token (SyxLexer *lexer)
EXPORT syx_char * syx_lexer_next_chunk (SyxLexer *lexer)
EXPORT SyxToken syx_lexer_get_last_token (SyxLexer *lexer)
EXPORT syx_char syx_lexer_get_last_char (SyxLexer *lexer)
INLINE syx_char syx_lexer_push_back (SyxLexer *lexer)
Typedef Documentation
typedef struct SyxLexer SyxLexer
Definition at line 61 of file syx-lexer.h.
typedef typedefSYX_BEGIN_DECLS struct SyxToken SyxToken
Definition at line 40 of file syx-lexer.h.
Function Documentation
EXPORT syx_char syx_lexer_forward (SyxLexer * lexer)
Get the next character or 0
Definition at line 419 of file syx-lexer.c.
Referenced by syx_lexer_next_token().
EXPORT void syx_lexer_free (SyxLexer * lexer, syx_bool free_text)
Frees the memory allocated by syx_lexer_new.
Parameters:
free_text TRUE frees the text
Definition at line 86 of file syx-lexer.c.
Referenced by syx_cold_file_in(), and syx_parser_free().
EXPORT syx_char syx_lexer_get_last_char (SyxLexer * lexer)
Returns the last character returned by syx_lexer_forward
Definition at line 555 of file syx-lexer.c.
Referenced by syx_lexer_push_back().
EXPORT SyxToken syx_lexer_get_last_token (SyxLexer * lexer)
Returns the last token returned by syx_lexer_next_token
Definition at line 548 of file syx-lexer.c.
EXPORT SyxLexer* syx_lexer_new (syx_symbol text)
Creates a new lexer to parse the code.
Parameters:
text the code
Returns:
A new SyxLexer
Definition at line 65 of file syx-lexer.c.
Referenced by syx_cold_file_in(), and syx_cold_parse_methods().
EXPORT syx_char* syx_lexer_next_chunk (SyxLexer * lexer)
Get the next chunk of code separated ending with an exlamation mark (!).
Returns:
A string containing the chunk without the exlamation mark. It must be freed once it's not needed anymore
Definition at line 513 of file syx-lexer.c.
Referenced by syx_cold_parse_methods().
EXPORT SyxToken syx_lexer_next_token (SyxLexer * lexer)
Returns the next token parsed by the lexer
Definition at line 439 of file syx-lexer.c.
Referenced by syx_cold_parse(), syx_cold_parse_methods(), syx_lexer_next_chunk(), and syx_parser_parse().
INLINE syx_char syx_lexer_push_back (SyxLexer * lexer)
Move backward the text pointer
Definition at line 84 of file syx-lexer.h.
Referenced by syx_lexer_next_token().
EXPORT void syx_token_free (SyxToken token)
Frees the memory allocated for a SyxToken.
The only way the token can be freed is only when it holds a string. In that case, the string is freed
Definition at line 101 of file syx-lexer.c.
Referenced by syx_cold_parse(), syx_cold_parse_methods(), and syx_lexer_next_chunk().
Documented by Luca Bruno and ScaccoMatto