Syx: syx/syx-object.c File Reference
syx-object.c File Reference
#include "syx-memory.h"
#include "syx-object.h"
#include "syx-interp.h"
#include "syx-error.h"
#include "syx-enums.h"
#include "syx-utils.h"
#include "syx-types.h"
#include "syx-scheduler.h"
#include "syx-profile.h"
#include <stdio.h>
#include <gmp.h>
Functions
void syx_object_initialize (SyxOop oop)
void syx_object_resize (SyxOop object, syx_varsize size)
SyxOop syx_metaclass_new (SyxOop supermetaclass)
SyxOop syx_class_new (SyxOop superclass)
SyxOop syx_large_integer_new (syx_symbol string, syx_int32 base)
SyxOop syx_large_integer_new_mpz (syx_pointer mpz)
SyxOop syx_large_integer_new_integer (syx_int32 i)
SyxOop syx_process_new (void)
syx_bool syx_array_remove (SyxOop array, SyxOop element)
void syx_array_add (SyxOop array, SyxOop element, syx_bool unique)
SyxOop syx_symbol_new (syx_symbol symbol)
syx_int32 syx_string_hash (syx_symbol string)
syx_int32 syx_dictionary_index_of (SyxOop dict, syx_symbol key, syx_int32 hash, syx_bool return_nil_index)
SyxOop syx_dictionary_binding_at_symbol (SyxOop dict, syx_symbol key)
SyxOop syx_dictionary_binding_at_symbol_if_absent (SyxOop dict, syx_symbol key, SyxOop object)
SyxOop syx_dictionary_bind (SyxOop binding)
SyxOop syx_dictionary_bind_if_absent (SyxOop binding, SyxOop object)
void syx_dictionary_bind_set_value (SyxOop binding, SyxOop value)
SyxOop syx_dictionary_at_symbol (SyxOop dict, syx_symbol key)
SyxOop syx_dictionary_at_symbol_if_absent (SyxOop dict, syx_symbol key, SyxOop object)
void syx_dictionary_rehash (SyxOop dict)
void syx_dictionary_at_symbol_put (SyxOop dict, SyxOop key, SyxOop value)
SyxOop syx_method_context_new (SyxOop method, SyxOop receiver, SyxOop arguments)
SyxOop syx_block_context_new (SyxOop closure, SyxOop arguments)
SyxOop syx_object_new_vars (SyxOop klass, syx_varsize vars_size)
SyxOop syx_object_new_size (SyxOop klass, syx_bool has_refs, syx_varsize size)
SyxOop syx_object_new_data (SyxOop klass, syx_bool has_refs, syx_varsize size, SyxOop *data)
SyxOop syx_object_copy (SyxOop object)
void syx_object_free (SyxOop object)
syx_bool syx_class_is_superclass_of (SyxOop klass, SyxOop subclass)
syx_symbol * syx_class_get_all_instance_variable_names (SyxOop klass)
SyxOop syx_class_lookup_method (SyxOop klass, syx_symbol selector)
SyxOop syx_class_lookup_method_binding (SyxOop klass, SyxOop binding)
void syx_semaphore_signal (SyxOop semaphore)
void syx_semaphore_wait (SyxOop semaphore)
Variables
SyxOop syx_nil
SyxOop syx_true
SyxOop syx_false
SyxOop syx_metaclass_class
SyxOop syx_undefined_object_class
SyxOop syx_true_class
SyxOop syx_false_class
SyxOop syx_small_integer_class
SyxOop syx_character_class
SyxOop syx_cpointer_class
SyxOop syx_large_integer_class = 0
SyxOop syx_float_class
SyxOop syx_symbol_class
SyxOop syx_string_class
SyxOop syx_byte_array_class
SyxOop syx_array_class
SyxOop syx_variable_binding_class
SyxOop syx_dictionary_class
SyxOop syx_compiled_method_class
SyxOop syx_compiled_block_class
SyxOop syx_block_closure_class
SyxOop syx_method_context_class
SyxOop syx_block_context_class
SyxOop syx_process_class
SyxOop syx_processor_scheduler_class
SyxOop syx_symbols
SyxOop syx_globals
Function Documentation
void syx_array_add (SyxOop array, SyxOop element, syx_bool unique)
Add an element to an Array.
Parameters:
unique TRUE if the element shouldn't be added if already present in the array
Definition at line 289 of file syx-object.c.
Referenced by syx_class_new(), and syx_metaclass_new().
syx_bool syx_array_remove (SyxOop array, SyxOop element)
Remove an element from an Array.
Returns:
TRUE if element was found and removed, else FALSE
Definition at line 260 of file syx-object.c.
SyxOop syx_block_context_new (SyxOop closure, SyxOop arguments)
Same as syx_method_context_new but for BlockContexts. The receiver is guessed by looking at the outer context.
Parameters:
closure a BlockClosure
Definition at line 694 of file syx-object.c.
Referenced by syx_interp_frame_to_context().
syx_symbol* syx_class_get_all_instance_variable_names (SyxOop klass)
Get a list of all instance variable names defined in a class.
The returned list is ordered to be used by the interpreter to access the variables directly using the list index.
Returns:
A syx_symbol list or NULL. The list must be freed once unused
Definition at line 868 of file syx-object.c.
Referenced by syx_parser_new().
syx_bool syx_class_is_superclass_of (SyxOop klass, SyxOop subclass)
Check if a class is a superclass of another one.
Parameters:
class a class
subclass a class that should be a subclass of the former
Returns:
TRUE if the first is a superclass of the second
Definition at line 847 of file syx-object.c.
SyxOop syx_class_lookup_method (SyxOop klass, syx_symbol selector)
Returns a method in a class having the given selector.
Returns:
syx_nil if no method has been found
Definition at line 905 of file syx-object.c.
Referenced by syx_send_binary_message(), syx_send_unary_message(), and syx_vsend_message().
SyxOop syx_class_lookup_method_binding (SyxOop klass, SyxOop binding)
A mix between syx_class_lookup_method and syx_dictionary_bind_if_absent.
Returns:
syx_nil if no method has been found
Definition at line 929 of file syx-object.c.
SyxOop syx_class_new (SyxOop superclass)
Creates a new class.
This function automatically creates the metaclass for the new class with syx_metaclass_new. The new class is an instance of the metaclass.
Parameters:
superclass the superclass of the new class
Definition at line 161 of file syx-object.c.
SyxOop syx_dictionary_at_symbol (SyxOop dict, syx_symbol key)
Lookup a key by symbol in the dictionary. Raise an error if not found.
Take care the dictionary MUST contain only symbol keys
Definition at line 576 of file syx-object.c.
SyxOop syx_dictionary_at_symbol_if_absent (SyxOop dict, syx_symbol key, SyxOop object)
Lookup a key by symbol in the dictionary. Return the given object if not found.
Take care the dictionary MUST contain only key symbols
Definition at line 594 of file syx-object.c.
Referenced by syx_class_lookup_method().
void syx_dictionary_at_symbol_put (SyxOop dict, SyxOop key, SyxOop value)
Insert key -> value in the dictionary
Definition at line 635 of file syx-object.c.
Referenced by syx_cold_parse_methods(), and syx_dictionary_rehash().
SyxOop syx_dictionary_bind (SyxOop binding)
Binds a VariableBinding returned by syx_dictionary_binding_at_symbol. Raise an exception if not bound.
The function get the dictionary entry at the index (the value of the given association) then compare the two keys. If they're equal, then return the value of the dictionary entry; if not, lookup the key and change the the index of the binding.
Returns:
The bound Object
Definition at line 467 of file syx-object.c.
SyxOop syx_dictionary_bind_if_absent (SyxOop binding, SyxOop object)
Binds a VariableBinding returned by syx_dictionary_binding_at_symbol. Return the given object if not found.
The function get the dictionary entry at the index (the value of the given association) then compare the two keys. If they're equal, then return the value of the dictionary entry; if not, lookup the key and change the the index of the binding.
Returns:
The bound Object
Definition at line 505 of file syx-object.c.
Referenced by syx_class_lookup_method_binding().
void syx_dictionary_bind_set_value (SyxOop binding, SyxOop value)
Set the object value of the binding returned by syx_dictionary_binding_at_symbol. Raise an exception if not found.
The function does the same thing ot syx_dictionary_bind, except that it sets the value in the Dictionary entry
Definition at line 540 of file syx-object.c.
SyxOop syx_dictionary_binding_at_symbol (SyxOop dict, syx_symbol key)
Create an association key -> index to be used as binding. Raise an error if not found.
Take care the dictionary MUST contain only key symbols
Returns:
An Association
Definition at line 426 of file syx-object.c.
SyxOop syx_dictionary_binding_at_symbol_if_absent (SyxOop dict, syx_symbol key, SyxOop object)
Create an association key -> index to be used as binding. Return the given object if not found.
Take care the dictionary MUST contain only symbol keys
Returns:
An Association
Definition at line 448 of file syx-object.c.
syx_int32 syx_dictionary_index_of (SyxOop dict, syx_symbol key, syx_int32 hash, syx_bool return_nil_index)
Returns the index of the given symbol, the index of an empty entry or -1 if the key was not found.
Take care the dictionary MUST contain only key symbols
Parameters:
hash the hash code of the key symbol
return_nil_index if TRUE returns the index of the first nil entry
Definition at line 379 of file syx-object.c.
Referenced by syx_dictionary_at_symbol(), syx_dictionary_at_symbol_if_absent(), syx_dictionary_at_symbol_put(), syx_dictionary_bind(), syx_dictionary_bind_if_absent(), syx_dictionary_bind_set_value(), syx_dictionary_binding_at_symbol(), syx_dictionary_binding_at_symbol_if_absent(), and syx_symbol_new().
void syx_dictionary_rehash (SyxOop dict)
Grow the dictionary and rehash all data
Definition at line 605 of file syx-object.c.
Referenced by syx_dictionary_at_symbol_put(), and syx_symbol_new().
SyxOop syx_large_integer_new (syx_symbol string, syx_int32 base)
Create a new LargeInteger.
This function is available only if Syx has been linked with the GMP library
Parameters:
string a textual representation of the number
base the radix of the representation
Definition at line 185 of file syx-object.c.
SyxOop syx_large_integer_new_integer (syx_int32 i)
Transform a 32-bit integer to a multiple precision integer.
This function is available only if Syx has been linked with the GMP library
Definition at line 215 of file syx-object.c.
SyxOop syx_large_integer_new_mpz (syx_pointer mpz)
Create a new LargeInteger with the given mpz
Definition at line 199 of file syx-object.c.
SyxOop syx_metaclass_new (SyxOop supermetaclass)
Creates a new metaclass.
The metaclass will be an instance of the Metaclass class. Instance size is inherited by superclass
Parameters:
supermetaclass the superclass of the new metaclass
Definition at line 139 of file syx-object.c.
Referenced by syx_build_basic(), and syx_class_new().
SyxOop syx_method_context_new (SyxOop method, SyxOop receiver, SyxOop arguments)
Create a new MethodContext.
Parameters:
method a CompiledMethod
receiver an Object receiving the message
arguments the arguments passed to the message
Definition at line 665 of file syx-object.c.
Referenced by syx_interp_frame_to_context(), syx_send_binary_message(), syx_send_unary_message(), and syx_vsend_message().
SyxOop syx_object_copy (SyxOop object)
Make a shallow copy of an object
Definition at line 776 of file syx-object.c.
void syx_object_free (SyxOop object)
Frees all the memory used by the object.
If the class has finalizationRequest set to true, perform finalize on the object
Definition at line 814 of file syx-object.c.
void syx_object_initialize (SyxOop oop)
Initialize a class from the Smalltalk-side
Create a new process, a new context and send the initialize message to the class. The process is executed in blocking mode.
Parameters:
class the class to be initialized
Definition at line 95 of file syx-object.c.
Referenced by syx_semaphore_new().
SyxOop syx_object_new_data (SyxOop klass, syx_bool has_refs, syx_varsize size, SyxOop * data)
Create a new object of the given size with the given data.
Parameters:
has_refs specify if the created object must be Object indexable or Byte indexable
size number of objects/bytes to hold
data the data of the object (must be an array of SyxOop or syx_int8)
Definition at line 763 of file syx-object.c.
Referenced by syx_array_new(), syx_byte_array_new(), syx_large_integer_new(), syx_large_integer_new_integer(), syx_large_integer_new_mpz(), syx_string_new(), syx_string_new_ref(), and syx_symbol_new().
SyxOop syx_object_new_size (SyxOop klass, syx_bool has_refs, syx_varsize size)
Create a new object of the given size.
Parameters:
has_refs specify if the created object must be Object indexable or Byte indexable
size number of objects/bytes to hold
Definition at line 743 of file syx-object.c.
Referenced by syx_array_new_size(), syx_byte_array_new_size(), syx_dictionary_new(), and syx_float_new().
SyxOop syx_object_new_vars (SyxOop klass, syx_varsize vars_size)
Create a new object specifying an arbitrary number of instance variables.
Parameters:
class the class of the new instance
vars_size number of instance variables the instance must hold
Definition at line 721 of file syx-object.c.
void syx_object_resize (SyxOop object, syx_varsize size)
Resize SyxObject::data to the given size, being careful of object indexables and byte indexables.
Warning, if the new size is lesser than the current, the data at the end of the array will be lost
Definition at line 116 of file syx-object.c.
Referenced by syx_array_remove().
SyxOop syx_process_new (void)
Create a new suspended Process and schedule it.
Parameters:
context a MethodContext or BlockContext
Definition at line 234 of file syx-object.c.
Referenced by syx_build_basic(), syx_do_it_blocking(), syx_file_in_blocking(), syx_initialize_system(), syx_memory_clear(), syx_object_free(), syx_object_initialize(), and syx_signal().
void syx_semaphore_signal (SyxOop semaphore)
Send a signal to a Semaphore to wake up waiting processes.
The function is thread-safe
Definition at line 954 of file syx-object.c.
void syx_semaphore_wait (SyxOop semaphore)
Put the active process in waiting state until semaphore is signaled.
The function is thread-safe
Definition at line 990 of file syx-object.c.
syx_int32 syx_string_hash (syx_symbol string)
Returns the hash of a String
Definition at line 358 of file syx-object.c.
Referenced by syx_dictionary_at_symbol(), syx_dictionary_at_symbol_if_absent(), syx_dictionary_binding_at_symbol(), syx_dictionary_binding_at_symbol_if_absent(), and syx_symbol_new().
SyxOop syx_symbol_new (syx_symbol symbol)
Returns a Symbol instance.
Lookups into syx_symbols dictionary to check the existance of the symbol, otherwise create a new one and insert it into the dictionary.
Parameters:
symbol a plain constant string
Definition at line 315 of file syx-object.c.
Referenced by syx_build_basic(), syx_bytecode_gen_message(), syx_dictionary_at_symbol(), syx_dictionary_binding_at_symbol(), syx_fetch_basic(), and syx_scheduler_init().
Variable Documentation
SyxOop syx_array_class
Definition at line 62 of file syx-object.c.
Referenced by syx_array_new(), syx_array_new_size(), syx_build_basic(), and syx_fetch_basic().
SyxOop syx_block_closure_class
Definition at line 62 of file syx-object.c.
Referenced by syx_block_closure_new(), syx_fetch_basic(), and syx_memory_save_image().
SyxOop syx_block_context_class
Definition at line 62 of file syx-object.c.
Referenced by syx_block_context_new(), syx_fetch_basic(), and syx_interp_enter_context().
SyxOop syx_byte_array_class
Definition at line 62 of file syx-object.c.
Referenced by syx_build_basic(), syx_byte_array_new(), syx_byte_array_new_size(), and syx_fetch_basic().
SyxOop syx_character_class
Definition at line 50 of file syx-object.c.
Referenced by syx_build_basic(), syx_fetch_basic(), and syx_object_get_class().
SyxOop syx_compiled_block_class
Definition at line 62 of file syx-object.c.
Referenced by syx_fetch_basic().
SyxOop syx_compiled_method_class
Definition at line 62 of file syx-object.c.
Referenced by syx_fetch_basic().
SyxOop syx_cpointer_class
Definition at line 50 of file syx-object.c.
Referenced by syx_fetch_basic(), and syx_object_get_class().
SyxOop syx_dictionary_class
Definition at line 62 of file syx-object.c.
Referenced by syx_build_basic(), syx_dictionary_new(), and syx_fetch_basic().
SyxOop syx_false
Definition at line 50 of file syx-object.c.
Referenced by syx_build_basic(), syx_fetch_basic(), syx_process_new(), syx_scheduler_remove_process(), and syx_semaphore_signal().
SyxOop syx_false_class
Definition at line 50 of file syx-object.c.
SyxOop syx_float_class
Definition at line 62 of file syx-object.c.
Referenced by syx_fetch_basic(), and syx_float_new().
SyxOop syx_globals
Definition at line 62 of file syx-object.c.
Referenced by syx_build_basic(), syx_initialize_system(), syx_memory_gc(), syx_memory_load_image(), and syx_memory_save_image().
SyxOop syx_large_integer_class = 0
Definition at line 62 of file syx-object.c.
Referenced by syx_fetch_basic(), syx_large_integer_new(), syx_large_integer_new_integer(), and syx_large_integer_new_mpz().
SyxOop syx_metaclass_class
Definition at line 50 of file syx-object.c.
Referenced by syx_build_basic(), syx_fetch_basic(), and syx_metaclass_new().
SyxOop syx_method_context_class
Definition at line 62 of file syx-object.c.
Referenced by syx_fetch_basic(), and syx_method_context_new().
SyxOop syx_nil
Definition at line 50 of file syx-object.c.
Referenced by syx_build_basic(), syx_bytecode_gen_message(), syx_class_lookup_method(), syx_class_lookup_method_binding(), syx_dictionary_bind(), syx_dictionary_binding_at_symbol(), syx_fetch_basic(), syx_interp_frame_to_context(), syx_large_integer_new(), syx_large_integer_new_integer(), syx_large_integer_new_mpz(), syx_object_get_class(), syx_scheduler_init(), syx_scheduler_remove_process(), syx_send_unary_message(), syx_signal_create_context(), syx_string_new(), syx_string_new_ref(), and syx_symbol_new().
SyxOop syx_process_class
Definition at line 62 of file syx-object.c.
Referenced by syx_fetch_basic(), and syx_process_new().
SyxOop syx_processor_scheduler_class
Definition at line 62 of file syx-object.c.
Referenced by syx_fetch_basic(), and syx_scheduler_init().
SyxOop syx_small_integer_class
Definition at line 50 of file syx-object.c.
Referenced by syx_build_basic(), syx_fetch_basic(), and syx_object_get_class().
SyxOop syx_string_class
Definition at line 62 of file syx-object.c.
Referenced by syx_build_basic(), syx_fetch_basic(), syx_string_new(), and syx_string_new_ref().
SyxOop syx_symbol_class
Definition at line 62 of file syx-object.c.
Referenced by syx_build_basic(), syx_fetch_basic(), and syx_symbol_new().
SyxOop syx_symbols
Definition at line 62 of file syx-object.c.
Referenced by syx_build_basic(), syx_memory_gc(), syx_memory_load_image(), syx_memory_save_image(), and syx_symbol_new().
SyxOop syx_true
Definition at line 50 of file syx-object.c.
Referenced by syx_build_basic(), syx_fetch_basic(), syx_process_new(), syx_scheduler_add_process(), and syx_semaphore_wait().
SyxOop syx_true_class
Definition at line 50 of file syx-object.c.
SyxOop syx_undefined_object_class
Definition at line 50 of file syx-object.c.
Referenced by syx_fetch_basic(), and syx_object_get_class().
SyxOop syx_variable_binding_class
Definition at line 62 of file syx-object.c.
Referenced by syx_build_basic(), syx_fetch_basic(), and syx_variable_binding_new().
Documented by Luca Bruno and ScaccoMatto