Syx: syx/syx-interp.h File Reference
syx-interp.h File Reference
#include "syx-object.h"
#include "syx-types.h"
#include "syx-scheduler.h"
#include "syx-init.h"
Data Structures
struct SyxInterpFrame
struct SyxInterpState
struct SyxPrimitiveEntry
Defines
#define SYX_INTERP_STATE_NEW {0, 0, 0, 0, 0, 0, 0, 0, 0, {0}, 0}
#define SYX_PRIM_RETURN(object)
#define SYX_PRIM_YIELD(object)
#define SYX_PRIM_FAIL
#define SYX_PRIM_ARGS(count)
#define SYX_PRIMITIVES_MAX 112
#define SYX_FUNC_PRIMITIVE(name)
#define SYX_FUNC_INTERPRETER(name)
#define syx_interp_stack_push(oop) (*(_syx_interp_state.frame->stack++) = (oop))
#define syx_interp_stack_pop() (*(--_syx_interp_state.frame->stack))
#define syx_interp_stack_peek() (*(_syx_interp_state.frame->stack-1))
Typedefs
typedef struct SyxInterpFrame SyxInterpFrame
typedef struct SyxInterpState SyxInterpState
typedef syx_bool(* SyxPrimitiveFunc)(SyxInterpState *es, SyxOop method)
typedef struct SyxPrimitiveEntry SyxPrimitiveEntry
typedef syx_bool(* SyxInterpreterFunc)(syx_uint16 argument)
Functions
EXPORT SyxInterpFrame * syx_interp_context_to_frame (SyxOop context)
EXPORT SyxOop syx_interp_frame_to_context (SyxOop stack, SyxInterpFrame *frame)
INLINE SyxPrimitiveEntry * syx_primitive_get_entry (syx_int32 index)
EXPORT syx_int32 syx_primitive_get_index (syx_symbol name)
EXPORT void syx_interp_init (void)
EXPORT void syx_interp_quit (void)
EXPORT syx_bool syx_interp_swap_context (SyxOop process, SyxOop context)
EXPORT syx_bool syx_interp_enter_context (SyxOop process, SyxOop context)
EXPORT syx_bool syx_interp_leave_and_answer (SyxOop return_object, syx_bool use_stack_return)
INLINE syx_bool syx_interp_call_primitive (syx_int16 primitive, SyxOop method)
EXPORT void syx_process_execute_scheduled (SyxOop process)
EXPORT void syx_process_execute_blocking (SyxOop process)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_instance)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_argument)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_temporary)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_literal)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_constant)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_binding_variable)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_array)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_block_closure)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_assign_instance)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_assign_temporary)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_assign_binding_variable)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_mark_arguments)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_send_message)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_send_super)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_send_unary)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_send_binary)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_do_special)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_do_extended)
Define Documentation
#define SYX_FUNC_INTERPRETER (name)
Value:
syx_bool                                \
  name (syx_uint16 argument)
Definition at line 140 of file syx-interp.h.
#define SYX_FUNC_PRIMITIVE (name)
Value:
syx_bool                                                \
  name (SyxInterpState *es, SyxOop method)
Definition at line 107 of file syx-interp.h.
#define syx_interp_stack_peek () (*(_syx_interp_state.frame->stack-1))
Peek the last object pushed into the stack
Definition at line 154 of file syx-interp.h.
#define syx_interp_stack_pop () (*(--_syx_interp_state.frame->stack))
Pop an object from the stack
Definition at line 151 of file syx-interp.h.
#define syx_interp_stack_push (oop) (*(_syx_interp_state.frame->stack++) = (oop))
Push an object into the stack
Definition at line 148 of file syx-interp.h.
Referenced by syx_interp_call_primitive(), and syx_interp_leave_and_answer().
#define SYX_INTERP_STATE_NEW {0, 0, 0, 0, 0, 0, 0, 0, 0, {0}, 0}
Definition at line 35 of file syx-interp.h.
Referenced by syx_interp_enter_context(), and syx_interp_swap_context().
#define SYX_PRIM_ARGS (count)
Value:
if (count > _syx_interp_state.message_arguments_count)       \
    {                                                          \
      SYX_PRIM_FAIL;                                           \
    }
Assert the number of minimum number of arguments given. Call SYX_PRIM_FAIL if assert fails
Definition at line 97 of file syx-interp.h.
#define SYX_PRIM_FAIL
Value:
_syx_interp_frame_prepare_new (&_syx_interp_state, method);           \
  return FALSE
Enter the method which contains the primitive call
Definition at line 92 of file syx-interp.h.
Referenced by syx_plugin_call(), and syx_plugin_call_interp().
#define SYX_PRIM_RETURN (object)
Value:
syx_interp_stack_push (object);                                       \
  return TRUE
Back to the interpreter and push object into the stack
Definition at line 82 of file syx-interp.h.
#define SYX_PRIM_YIELD (object)
Value:
syx_interp_stack_push (object);                \
  return FALSE
Same as SYX_PRIM_RETURN but the process yield the control
Definition at line 87 of file syx-interp.h.
#define SYX_PRIMITIVES_MAX 112
The number of primitives
Definition at line 104 of file syx-interp.h.
Referenced by syx_primitive_get_entry(), and syx_primitive_get_index().
Typedef Documentation
typedef struct SyxInterpFrame SyxInterpFrame
Definition at line 42 of file syx-interp.h.
typedef syx_bool(* SyxInterpreterFunc)(syx_uint16 argument)
Definition at line 139 of file syx-interp.h.
typedef struct SyxInterpState SyxInterpState
Definition at line 58 of file syx-interp.h.
typedef struct SyxPrimitiveEntry SyxPrimitiveEntry
Definition at line 111 of file syx-interp.h.
typedef syx_bool(* SyxPrimitiveFunc)(SyxInterpState *es, SyxOop method)
Definition at line 106 of file syx-interp.h.
Function Documentation
EXPORT SYX_FUNC_INTERPRETER (syx_interp_do_extended)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_do_special)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_send_binary)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_send_unary)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_send_super)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_send_message)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_mark_arguments)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_assign_binding_variable)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_assign_temporary)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_assign_instance)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_block_closure)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_array)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_binding_variable)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_constant)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_literal)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_temporary)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_argument)
EXPORT SYX_FUNC_INTERPRETER (syx_interp_push_instance)
INLINE syx_bool syx_interp_call_primitive (syx_int16 primitive, SyxOop method)
Calls a primitive.
Parameters:
primitive the primitive index
method the method in which the primitive is defined
Definition at line 168 of file syx-interp.h.
EXPORT SyxInterpFrame* syx_interp_context_to_frame (SyxOop context)
Returns the frame associated to the given context
Definition at line 165 of file syx-interp.c.
Referenced by syx_interp_swap_context().
EXPORT syx_bool syx_interp_enter_context (SyxOop process, SyxOop context)
Enters a new MethodContext or BlockContext.
Returns:
FALSE if the context was syx_nil
Definition at line 271 of file syx-interp.c.
Referenced by syx_build_basic(), syx_do_it_blocking(), syx_file_in_blocking(), syx_initialize_system(), syx_memory_clear(), syx_object_free(), syx_object_initialize(), syx_signal(), and syx_signal_does_not_understand().
EXPORT SyxOop syx_interp_frame_to_context (SyxOop stack, SyxInterpFrame * frame)
Creates a MethodContext or BlockContext from a frame
Parameters:
stack the OOP of the whole stack, e.g. SYX_PROCESS_STACK (aProcess). This will not be used if the frame has been detached.
Returns:
a new context
Definition at line 179 of file syx-interp.c.
EXPORT void syx_interp_init (void)
Initialize the interpreter to be ready to execute processes.
This function is called internally by Syx and should not be called from user applications.
Definition at line 219 of file syx-interp.c.
Referenced by syx_fetch_basic().
EXPORT syx_bool syx_interp_leave_and_answer (SyxOop return_object, syx_bool use_stack_return)
Leaves the current frame and push an object into the returning context.
Use the stack return frame use_stack_return is specified, otherwise use the parent frame. Then sets the returned object variable of the process to the specified object. Finally swap the context with the new one. Terminate the process if no valid return frame is found.
Parameters:
return_object the object to be pushed into the returning context
use_stack_return TRUE to use the stack return frame, FALSE to use the parent frame
Returns:
FALSE if no valid return frame is found
Definition at line 334 of file syx-interp.c.
EXPORT void syx_interp_quit (void)
Finalize the execution of processes and free all the memory used by the interpreter.
This function is called internally by Syx e should not be called from user applications
Definition at line 229 of file syx-interp.c.
Referenced by syx_quit().
EXPORT syx_bool syx_interp_swap_context (SyxOop process, SyxOop context)
Swap the current context with the given one. The context must be already existing in the process stack.
Returns:
FALSE if the context was syx_nil
Definition at line 240 of file syx-interp.c.
INLINE SyxPrimitiveEntry* syx_primitive_get_entry (syx_int32 index)
Returns the entry of a primitive at a given index
Definition at line 124 of file syx-interp.h.
Referenced by syx_interp_call_primitive().
EXPORT syx_int32 syx_primitive_get_index (syx_symbol name)
Returns the index of a primitive having a specific name
Definition at line 2104 of file syx-primitives.c.
EXPORT void syx_process_execute_blocking (SyxOop process)
Same as syx_process_execute_scheduled but does not take care about the byteslice counter, and control is not yield until the process is terminated.
Definition at line 390 of file syx-interp.c.
Referenced by syx_build_basic(), syx_do_it_blocking(), syx_file_in_blocking(), syx_initialize_system(), syx_memory_clear(), syx_object_free(), syx_object_initialize(), and syx_signal().
EXPORT void syx_process_execute_scheduled (SyxOop process)
Executes the given process and returns once the byteslice is reached, no more instructions left or yield has been requested.
Parameters:
process must not be nil
Definition at line 368 of file syx-interp.c.
Referenced by syx_scheduler_iterate(), and syx_scheduler_run().
Documented by Luca Bruno and ScaccoMatto